% Draw large bounding box:
clf;
xstart = 0;
ystart = 0;

xlen = 1;
ylen = 1;
figure(1)
rectangle('position', [xstart, ystart, xlen, ylen])

% Draw smaller boxes
dx = 0.2;
dy = 0.2;

nx = floor(xlen/dx);
ny = floor(ylen/dy);

for i = 1:nx
    x = xstart + (i-1)*dx;
    for j = 1:ny
        y = ystart + (j-1)*dy;
        rectangle('position', [x, y, dx, dy])
    end
end
axis square
set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'off'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'off'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'YTick'       , [0,1], ...
    'XTick'       , [0,1], ...
    'LineWidth'   , 1         );
%%

[hx,hy] = format_ticks(gca,...
    {'$0$','$x_0$','$x_1$','$...$','$x_{m-2}$','$x_{m-1}$','$1$'},...
    {'$0$','$y_0$','$y_1$','$...$','$y_{n-2}$','$y_{n-1}$','$1$'},...
    [0,0.1,0.3,0.5,0.7,0.9,1],...
    [0,0.1,0.3,0.5,0.7,0.9,1],...
    0,0,[],...
    'FontSize',16,'FontWeight','Bold');
%% 1st 2nd row
% DESCRIPTIVE TEXT

yDummy = 0.165;
for i=1:2
    annotation(gcf,'textbox',...
        [0.25 i*yDummy 0.05 0.05],...
        'String',{sprintf('q_{0,%1d}',i-1)},...
        'LineStyle','none','Fontsize',14);
    annotation(gcf,'textbox',...
        [0.375 i*yDummy 0.05 0.05],...
        'String',{sprintf('q_{1,%1d}',i-1)},...
        'LineStyle','none','Fontsize',14);
    annotation(gcf,'textbox',...
        [0.59 i*yDummy 0.05 0.05],...
        'String',{sprintf('q_{m-2,n-1}')},...
        'LineStyle','none','Fontsize',14);
    annotation(gcf,'textbox',...
        [0.71 i*yDummy 0.05 0.05],...
        'String',{sprintf('q_{m-1,n-1}')},...
        'LineStyle','none','Fontsize',14);
end

%% 4th row
% DESCRIPTIVE TEXT
annotation(gcf,'textbox',...
    [0.24 4*yDummy 0.05 0.05],...
    'String',{sprintf('q_{0,n-2}')},...
    'LineStyle','none','Fontsize',14);
annotation(gcf,'textbox',...
    [0.36 4*yDummy 0.05 0.05],...
    'String',{sprintf('q_{1,n-2}')},...
    'LineStyle','none','Fontsize',14);
annotation(gcf,'textbox',...
    [0.59 4*yDummy 0.05 0.05],...
    'String',{sprintf('q_{m-2,n-2}')},...
    'LineStyle','none','Fontsize',14);
annotation(gcf,'textbox',...
    [0.71 4*yDummy 0.05 0.05],...
    'String',{sprintf('q_{m-1,n-2}')},...
    'LineStyle','none','Fontsize',14);
%% 5th row
% DESCRIPTIVE TEXT

annotation(gcf,'textbox',...
    [0.24 5*yDummy 0.05 0.05],...
    'String',{sprintf('q_{0,n-1}')},...
    'LineStyle','none','Fontsize',14);
annotation(gcf,'textbox',...
    [0.36 5*yDummy 0.05 0.05],...
    'String',{sprintf('q_{1,n-1}')},...
    'LineStyle','none','Fontsize',14);
annotation(gcf,'textbox',...
    [0.59 5*yDummy 0.05 0.05],...
    'String',{sprintf('q_{m-2,n-1}')},...
    'LineStyle','none','Fontsize',14);
annotation(gcf,'textbox',...
    [0.71 5*yDummy 0.05 0.05],...
    'String',{sprintf('q_{m-1,n-1}')},...
    'LineStyle','none','Fontsize',14);
%% Print Plots
saveFigurePath = '/Users/kevin/Downloads/';

%% Plot 1
set(figure(1), 'PaperPositionMode', 'auto');
print('-depsc2', [saveFigurePath ...
    sprintf('gridForNumericalSchemePlot')]);